name: Check Example Executions

on:
  - push
  - pull_request

jobs:
  run_examples:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8, 3.9]
        torch-version: [1.9.0]
        include:
          - torch-version: 1.9.0
            torchvision-version: 0.10.0

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install nle dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install PyG dependencies
      run: |
        pip install torch==${{ matrix.torch-version }}+cpu torchvision==${{ matrix.torchvision-version }}+cpu -f https://download.pytorch.org/whl/torch_stable.html
        pip install torch-scatter -f https://data.pyg.org/whl/torch-${{ matrix.torch-version }}+cpu.html
        pip install torch-sparse -f https://data.pyg.org/whl/torch-${{ matrix.torch-version }}+cpu.html
        pip install torch-cluster -f https://data.pyg.org/whl/torch-${{ matrix.torch-version }}+cpu.html
        pip install torch-spline-conv -f https://data.pyg.org/whl/torch-${{ matrix.torch-version }}+cpu.html

    - name: Install latest PyG from github
      run: |
        pip install git+https://github.com/pyg-team/pytorch_geometric.git#egg=torch-geometric[full]

    - anem: Install latest PecanPy from github
      run: |
        pip install git+https://github.com/krishnanlab/PecanPy

    - name: Install NLEval
      run: |
        pip install -e .

    - name: Execute example scripts
      shell: bash
      run: |
        cd example
        for script in $(ls *.py); do
          echo Start runing example script: $script
          python $script
        done
